"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['main.py']
DATA_FILES = []
OPTIONS = {'argv_emulation': True}

setup(name="QAbsorb",
    version="1.0",
    author="Giuseppe Marco Randazzo",
    url="https://github.com/gmrandazzo/QAbsorb",
    license="LGPLv3",
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
